### ISSUE TITLE
Crash in NAMD + ROCFFT (large case)

### ISSUE THREAD

**Issue by etiennemlb** [ROCmSoftwarePlatform/rocFFT#573]
Crash in rocfft execute:

```
rocfft_setup
rocfft_plan_description_create,description,0x57fc8090
rocfft_plan_description_create,description,0x5bad6470
rocfft_plan_description_create,description,0x5bad6520
rocfft_plan_description_create,description,0x61228790
rocfft_plan_create,plan,0x5f410870,placement,inplace,transform_type,real_forward,precision,single,dimensions,3,lengths,[396,396,396],number_of_transforms,1,description,0x57fc8090
rocfft_plan_create,plan,0x598b8b60,placement,notinplace,transform_type,real_forward,precision,single,dimensions,3,lengths,[396,396,396],number_of_transforms,1,description,0x5bad6470
rocfft_plan_get_work_buffer_size,plan,0x5f410870,size_in_bytes ptr,0x7ffee54ea9b0,val,249651072
rocfft_plan_get_work_buffer_size,plan,0x598b8b60,size_in_bytes ptr,0x7ffee54ea9b0,val,249651072
rocfft_execution_info_set_work_buffer,info,0x584e1aa0,work_buffer,0x7f8932800000,size_in_bytes,249651072
rocfft_plan_description_destroy,description,0x57fc8090
rocfft_plan_description_destroy,description,0x5bad6470
rocfft_plan_description_destroy,description,0x5bad6520
rocfft_plan_description_destroy,description,0x61228790
rocfft_execution_info_create,info,0x59211290
rocfft_plan_description_create,description,0x61228790
rocfft_plan_description_create,description,0x5bad6520
rocfft_plan_description_create,description,0x5bad6470
rocfft_plan_description_create,description,0x57fc8090
rocfft_plan_create,plan,0x56566e70,placement,inplace,transform_type,real_inverse,precision,single,dimensions,3,lengths,[396,396,396],number_of_transforms,1,description,0x5bad6470
rocfft_plan_create,plan,0x5b5a3770,placement,notinplace,transform_type,real_inverse,precision,single,dimensions,3,lengths,[396,396,396],number_of_transforms,1,description,0x57fc8090
rocfft_plan_get_work_buffer_size,plan,0x56566e70,size_in_bytes ptr,0x7ffee54ea9b0,val,249651072
rocfft_plan_get_work_buffer_size,plan,0x5b5a3770,size_in_bytes ptr,0x7ffee54ea9b0,val,249651072
rocfft_execution_info_set_work_buffer,info,0x59211290,work_buffer,0x7f891ce00000,size_in_bytes,249651072
rocfft_plan_description_destroy,description,0x61228790
rocfft_plan_description_destroy,description,0x5bad6520
rocfft_plan_description_destroy,description,0x5bad6470
rocfft_plan_description_destroy,description,0x57fc8090
rocfft_execution_info_set_stream,info,0x584e1aa0,stream,0x7f8ce80747c0
rocfft_execution_info_set_stream,info,0x59211290,stream,0x7f8ce80747c0
rocfft_execution_info_create,info,0x7f890497bf30
rocfft_plan_description_create,description,0x7f8cd2fe6ff0
rocfft_plan_description_create,description,0x7f8cd2fe82e0
rocfft_plan_description_create,description,0x7f8cd2fd74c0
rocfft_plan_description_create,description,0x7f890497dd40
rocfft_plan_create,plan,0x7f890497de40,placement,inplace,transform_type,real_forward,precision,single,dimensions,3,lengths,[396,396,396],number_of_transforms,1,description,0x7f8cd2fe6ff0
rocfft_plan_create,plan,0x7f8cd31dcfb0,placement,notinplace,transform_type,real_forward,precision,single,dimensions,3,lengths,[396,396,396],number_of_transforms,1,description,0x7f8cd2fe82e0
rocfft_plan_get_work_buffer_size,plan,0x7f890497de40,size_in_bytes ptr,0x7f890409f9d0,val,249651072
rocfft_plan_get_work_buffer_size,plan,0x7f8cd31dcfb0,size_in_bytes ptr,0x7f890409f9d0,val,249651072
rocfft_execution_info_set_work_buffer,info,0x7f890497bf30,work_buffer,0x7f885ce00000,size_in_bytes,249651072
rocfft_plan_description_destroy,description,0x7f8cd2fe6ff0
rocfft_plan_description_destroy,description,0x7f8cd2fe82e0
rocfft_plan_description_destroy,description,0x7f8cd2fd74c0
rocfft_plan_description_destroy,description,0x7f890497dd40
rocfft_execution_info_create,info,0x7f8907d82bc0
rocfft_plan_description_create,description,0x7f890497dd40
rocfft_plan_description_create,description,0x7f8cd2fd74c0
rocfft_plan_description_create,description,0x7f8cd2fe82e0
rocfft_plan_description_create,description,0x7f8cd2fe6ff0
rocfft_plan_create,plan,0x7f8907d90d00,placement,inplace,transform_type,real_inverse,precision,single,dimensions,3,lengths,[396,396,396],number_of_transforms,1,description,0x7f8cd2fe82e0
rocfft_plan_create,plan,0x7f8907dc0990,placement,notinplace,transform_type,real_inverse,precision,single,dimensions,3,lengths,[396,396,396],number_of_transforms,1,description,0x7f8cd2fe6ff0
rocfft_plan_get_work_buffer_size,plan,0x7f8907d90d00,size_in_bytes ptr,0x7f890409f9d0,val,249651072
rocfft_plan_get_work_buffer_size,plan,0x7f8907dc0990,size_in_bytes ptr,0x7f890409f9d0,val,249651072
rocfft_execution_info_set_work_buffer,info,0x7f8907d82bc0,work_buffer,0x7f8844e00000,size_in_bytes,249651072
rocfft_plan_description_destroy,description,0x7f890497dd40
rocfft_plan_description_destroy,description,0x7f8cd2fd74c0
rocfft_plan_description_destroy,description,0x7f8cd2fe82e0
rocfft_plan_description_destroy,description,0x7f8cd2fe6ff0
rocfft_execution_info_set_stream,info,0x7f890497bf30,stream,0x7f8904971420
rocfft_execution_info_set_stream,info,0x7f8907d82bc0,stream,0x7f8904971420
rocfft_execute,plan,0x7f8cd31dcfb0,in_buffer,0x7f890409fb40,out_buffer,0x7f890409fb38,info,0x7f890497bf30
max grid size exceeded: r2c_even_post_Ndiv4_dim3_sp_CI_CI
max grid size exceeded: r2c_even_post_Ndiv4_dim3_sp_CI_CI
rocfft_cleanup
```

I get the following rocfft bench reproducer:

```
rocfft-bench --length 396 396 396 -b 1 -t 2 --precision single --itype 2 --otype 3 --istride 157608 398 1 --ostride 78804 199 1 --idist 62412768 --odist 31206384 --ioffset 0 0 --ooffset 0 0 
rocfft-bench --length 396 396 396 -b 1 -o -t 2 --precision single --itype 2 --otype 3 --istride 156816 396 1 --ostride 78804 199 1 --idist 62099136 --odist 31206384 --ioffset 0 0 --ooffset 0 0 
rocfft-bench --length 396 396 396 -b 1 -t 3 --precision single --itype 3 --otype 2 --istride 78804 199 1 --ostride 157608 398 1 --idist 31206384 --odist 62412768 --ioffset 0 0 --ooffset 0 0 
rocfft-bench --length 396 396 396 -b 1 -o -t 3 --precision single --itype 3 --otype 2 --istride 78804 199 1 --ostride 156816 396 1 --idist 31206384 --odist 62099136 --ioffset 0 0 --ooffset 0 0 
rocfft-bench --length 396 396 396 -b 1 -t 2 --precision single --itype 2 --otype 3 --istride 157608 398 1 --ostride 78804 199 1 --idist 62412768 --odist 31206384 --ioffset 0 0 --ooffset 0 0 
rocfft-bench --length 396 396 396 -b 1 -o -t 2 --precision single --itype 2 --otype 3 --istride 156816 396 1 --ostride 78804 199 1 --idist 62099136 --odist 31206384 --ioffset 0 0 --ooffset 0 0 
rocfft-bench --length 396 396 396 -b 1 -t 3 --precision single --itype 3 --otype 2 --istride 78804 199 1 --ostride 157608 398 1 --idist 31206384 --odist 62412768 --ioffset 0 0 --ooffset 0 0 
rocfft-bench --length 396 396 396 -b 1 -o -t 3 --precision single --itype 3 --otype 2 --istride 78804 199 1 --ostride 156816 396 1 --idist 31206384 --odist 62099136 --ioffset 0 0 --ooffset 0 0 
```

<details>

<summary>plan path</summary>

```
Kernel occupancy: 2
Kernel occupancy: 2
Kernel occupancy: 32
Kernel occupancy: 2
Kernel occupancy: 2
ExecPlan:
  deviceID: 0
*******************************************************************************
Work buffer size: 31206384
Work buffer ratio: 0.5025
Assignment strategy: BALANCE_BUFFER_FUSION

scheme: CS_REAL_3D_EVEN
dimension: 3
batch: 1
length: 396 396 396 
outputLength: 199 396 396 
iStrides: 1 396 156816 
oStrides: 1 199 78804 
iDist: 62099136
oDist: 31206384
direction: -1
placement: OP
single-precision
array type: R -> HI
SBRC_Trans_Type: NONE
Direct_to_from_Reg: FORCE_OFF_OR_NOT_SUPPORT
OB_USER_IN -> OB_USER_OUT
A -> B

    scheme: CS_REAL_TRANSFORM_EVEN
    dimension: 1
    batch: 1
    length: 396 396 396 
    outputLength: 199 396 396 
    iStrides: 1 396 156816 
    oStrides: 1 199 78804 
    iDist: 62099136
    oDist: 31206384
    direction: -1
    placement: OP
    single-precision
    array type: R -> CI
    SBRC_Trans_Type: NONE
    Direct_to_from_Reg: FORCE_OFF_OR_NOT_SUPPORT
    OB_USER_IN -> OB_TEMP
    A -> T

        scheme: CS_L1D_TRTRT
        dimension: 1
        batch: 1
        length: 198 396 396 
        iStrides: 1 198 78408 
        oStrides: 1 198 78408 
        iDist: 31049568
        oDist: 31049568
        direction: -1
        placement: OP
        single-precision
        array type: CI -> CI
        SBRC_Trans_Type: NONE
        Direct_to_from_Reg: FORCE_OFF_OR_NOT_SUPPORT
        OB_USER_IN -> OB_USER_OUT
        A -> B

            scheme: CS_KERNEL_STOCKHAM
            dimension: 1
            batch: 1
            length: 11 18 396 396 
            iStrides: 18 1 198 78408 
            oStrides: 1 11 198 78408 
            iDist: 31049568
            oDist: 31049568
            direction: -1
            placement: OP
            single-precision
            array type: CI -> CI
            SBRC_Trans_Type: NONE
            Direct_to_from_Reg: TRY_ENABLE_IF_SUPPORT
            OB_USER_IN -> OB_USER_OUT
            A -> B
            comment: TRFuseShim: fused CS_KERNEL_TRANSPOSE and following CS_KERNEL_STOCKHAM
            Leaf-Node: external-kernel configuration: 
                workgroup_size: 128
                trans_per_block: 128
                radices: [ 11 ]

            scheme: CS_KERNEL_TRANSPOSE
            dimension: 2
            batch: 1
            length: 11 18 396 396 
            outputLength: 18 11 396 396 
            iStrides: 1 11 198 78408 
            oStrides: 18 1 198 78408 
            iDist: 31049568
            oDist: 31049568
            direction: -1
            placement: OP
            single-precision
            array type: CI -> CI
            large1D: 198
            largeTwdBase: 8
            largeTwdSteps: 0
            large twiddle table length: 256
            SBRC_Trans_Type: NONE
            Direct_to_from_Reg: FORCE_OFF_OR_NOT_SUPPORT
            OB_USER_OUT -> OB_TEMP
            B -> T
            Leaf-Node: external-kernel configuration: 
                workgroup_size: 0
                trans_per_block: 1
                radices: [ ]

            scheme: CS_KERNEL_STOCKHAM
            dimension: 1
            batch: 1
            length: 18 11 396 396 
            outputLength: 11 18 396 396 
            iStrides: 1 18 198 78408 
            oStrides: 11 1 198 78408 
            iDist: 31049568
            oDist: 31049568
            direction: -1
            placement: OP
            single-precision
            array type: CI -> CI
            twiddle table length: 15
            SBRC_Trans_Type: NONE
            Direct_to_from_Reg: TRY_ENABLE_IF_SUPPORT
            OB_TEMP -> OB_USER_OUT
            T -> B
            comment: RTFuseShim: fused CS_KERNEL_STOCKHAM and following CS_KERNEL_TRANSPOSE
            Leaf-Node: external-kernel configuration: 
                workgroup_size: 60
                trans_per_block: 10
                radices: [ 3 6 ]

        scheme: CS_KERNEL_R_TO_CMPLX
        dimension: 1
        batch: 1
        length: 198 396 396 
        outputLength: 199 396 396 
        iStrides: 1 198 78408 
        oStrides: 1 199 78804 
        iDist: 31049568
        oDist: 31206384
        direction: -1
        placement: OP
        single-precision
        array type: CI -> CI
        twiddle table length: 99
        SBRC_Trans_Type: NONE
        Direct_to_from_Reg: FORCE_OFF_OR_NOT_SUPPORT
        OB_USER_OUT -> OB_TEMP
        B -> T
        Leaf-Node: external-kernel configuration: 
            workgroup_size: 0
            trans_per_block: 1
            radices: [ ]

    scheme: CS_KERNEL_TRANSPOSE_Z_XY
    dimension: 2
    batch: 1
    length: 199 396 396 
    outputLength: 396 396 199 
    iStrides: 1 199 78804 
    oStrides: 156816 1 396 
    iDist: 31206384
    oDist: 31206384
    direction: -1
    placement: OP
    single-precision
    array type: CI -> CI
    SBRC_Trans_Type: NONE
    Direct_to_from_Reg: FORCE_OFF_OR_NOT_SUPPORT
    OB_TEMP -> OB_USER_OUT
    T -> B
    Leaf-Node: external-kernel configuration: 
        workgroup_size: 0
        trans_per_block: 1
        radices: [ ]

    scheme: CS_L1D_TRTRT
    dimension: 1
    batch: 1
    length: 396 396 199 
    iStrides: 1 396 156816 
    oStrides: 1 396 156816 
    iDist: 31206384
    oDist: 31206384
    direction: -1
    placement: IP
    single-precision
    array type: CI -> CI
    SBRC_Trans_Type: NONE
    Direct_to_from_Reg: FORCE_OFF_OR_NOT_SUPPORT
    OB_USER_OUT -> OB_USER_OUT
    B -> B

        scheme: CS_KERNEL_TRANSPOSE
        dimension: 2
        batch: 1
        length: 22 18 396 199 
        outputLength: 18 22 396 199 
        iStrides: 1 22 396 156816 
        oStrides: 18 1 396 156816 
        iDist: 31206384
        oDist: 31206384
        direction: -1
        placement: OP
        single-precision
        array type: CI -> CI
        SBRC_Trans_Type: NONE
        Direct_to_from_Reg: FORCE_OFF_OR_NOT_SUPPORT
        OB_USER_OUT -> OB_TEMP
        B -> T
        Leaf-Node: external-kernel configuration: 
            workgroup_size: 0
            trans_per_block: 1
            radices: [ ]

        scheme: CS_KERNEL_STOCKHAM
        dimension: 1
        batch: 1733688
        length: 18 
        iStrides: 1 
        oStrides: 1 
        iDist: 18
        oDist: 18
        direction: -1
        placement: OP
        single-precision
        array type: CI -> CI
        twiddle table length: 15
        SBRC_Trans_Type: NONE
        Direct_to_from_Reg: TRY_ENABLE_IF_SUPPORT
        OB_TEMP -> OB_USER_OUT
        T -> B
        comment: collapsed contiguous high length(s) 22 396 199 into batch
        Leaf-Node: external-kernel configuration: 
            workgroup_size: 60
            trans_per_block: 10
            radices: [ 3 6 ]

        scheme: CS_KERNEL_TRANSPOSE
        dimension: 2
        batch: 1
        length: 18 22 396 199 
        outputLength: 22 18 396 199 
        iStrides: 1 18 396 156816 
        oStrides: 22 1 396 156816 
        iDist: 31206384
        oDist: 31206384
        direction: -1
        placement: OP
        single-precision
        array type: CI -> CI
        large1D: 396
        largeTwdBase: 8
        largeTwdSteps: 0
        large twiddle table length: 512
        SBRC_Trans_Type: NONE
        Direct_to_from_Reg: FORCE_OFF_OR_NOT_SUPPORT
        OB_USER_OUT -> OB_TEMP
        B -> T
        Leaf-Node: external-kernel configuration: 
            workgroup_size: 0
            trans_per_block: 1
            radices: [ ]

        scheme: CS_KERNEL_STOCKHAM
        dimension: 1
        batch: 1
        length: 22 18 396 199 
        outputLength: 18 22 396 199 
        iStrides: 1 22 396 156816 
        oStrides: 18 1 396 156816 
        iDist: 31206384
        oDist: 31206384
        direction: -1
        placement: OP
        single-precision
        array type: CI -> CI
        twiddle table length: 11
        SBRC_Trans_Type: NONE
        Direct_to_from_Reg: TRY_ENABLE_IF_SUPPORT
        OB_TEMP -> OB_USER_OUT
        T -> B
        comment: RTFuseShim: fused CS_KERNEL_STOCKHAM and following CS_KERNEL_TRANSPOSE
        Leaf-Node: external-kernel configuration: 
            workgroup_size: 64
            trans_per_block: 32
            radices: [ 11 2 ]

    scheme: CS_KERNEL_TRANSPOSE_Z_XY
    dimension: 2
    batch: 1
    length: 396 396 199 
    outputLength: 396 199 396 
    iStrides: 1 396 156816 
    oStrides: 78804 1 396 
    iDist: 31206384
    oDist: 31206384
    direction: -1
    placement: OP
    single-precision
    array type: CI -> CI
    SBRC_Trans_Type: NONE
    Direct_to_from_Reg: FORCE_OFF_OR_NOT_SUPPORT
    OB_USER_OUT -> OB_TEMP
    B -> T
    Leaf-Node: external-kernel configuration: 
        workgroup_size: 0
        trans_per_block: 1
        radices: [ ]

    scheme: CS_L1D_TRTRT
    dimension: 1
    batch: 1
    length: 396 199 396 
    iStrides: 1 396 78804 
    oStrides: 1 396 78804 
    iDist: 31206384
    oDist: 31206384
    direction: -1
    placement: IP
    single-precision
    array type: CI -> CI
    SBRC_Trans_Type: NONE
    Direct_to_from_Reg: FORCE_OFF_OR_NOT_SUPPORT
    OB_TEMP -> OB_TEMP
    T -> T

        scheme: CS_KERNEL_TRANSPOSE
        dimension: 2
        batch: 1
        length: 22 18 199 396 
        outputLength: 18 22 199 396 
        iStrides: 1 22 396 78804 
        oStrides: 18 1 396 78804 
        iDist: 31206384
        oDist: 31206384
        direction: -1
        placement: OP
        single-precision
        array type: CI -> CI
        SBRC_Trans_Type: NONE
        Direct_to_from_Reg: FORCE_OFF_OR_NOT_SUPPORT
        OB_TEMP -> OB_USER_OUT
        T -> B
        Leaf-Node: external-kernel configuration: 
            workgroup_size: 0
            trans_per_block: 1
            radices: [ ]

        scheme: CS_KERNEL_STOCKHAM
        dimension: 1
        batch: 1733688
        length: 18 
        iStrides: 1 
        oStrides: 1 
        iDist: 18
        oDist: 18
        direction: -1
        placement: OP
        single-precision
        array type: CI -> CI
        twiddle table length: 15
        SBRC_Trans_Type: NONE
        Direct_to_from_Reg: TRY_ENABLE_IF_SUPPORT
        OB_USER_OUT -> OB_TEMP
        B -> T
        comment: collapsed contiguous high length(s) 22 199 396 into batch
        Leaf-Node: external-kernel configuration: 
            workgroup_size: 60
            trans_per_block: 10
            radices: [ 3 6 ]

        scheme: CS_KERNEL_TRANSPOSE
        dimension: 2
        batch: 1
        length: 18 22 199 396 
        outputLength: 22 18 199 396 
        iStrides: 1 18 396 78804 
        oStrides: 22 1 396 78804 
        iDist: 31206384
        oDist: 31206384
        direction: -1
        placement: OP
        single-precision
        array type: CI -> CI
        large1D: 396
        largeTwdBase: 8
        largeTwdSteps: 0
        large twiddle table length: 512
        SBRC_Trans_Type: NONE
        Direct_to_from_Reg: FORCE_OFF_OR_NOT_SUPPORT
        OB_TEMP -> OB_USER_OUT
        T -> B
        Leaf-Node: external-kernel configuration: 
            workgroup_size: 0
            trans_per_block: 1
            radices: [ ]

        scheme: CS_KERNEL_STOCKHAM
        dimension: 1
        batch: 1
        length: 22 18 199 396 
        outputLength: 18 22 199 396 
        iStrides: 1 22 396 78804 
        oStrides: 18 1 396 78804 
        iDist: 31206384
        oDist: 31206384
        direction: -1
        placement: OP
        single-precision
        array type: CI -> CI
        twiddle table length: 11
        SBRC_Trans_Type: NONE
        Direct_to_from_Reg: TRY_ENABLE_IF_SUPPORT
        OB_USER_OUT -> OB_TEMP
        B -> T
        comment: RTFuseShim: fused CS_KERNEL_STOCKHAM and following CS_KERNEL_TRANSPOSE
        Leaf-Node: external-kernel configuration: 
            workgroup_size: 64
            trans_per_block: 32
            radices: [ 11 2 ]

    scheme: CS_KERNEL_TRANSPOSE_Z_XY
    dimension: 2
    batch: 1
    length: 396 199 396 
    outputLength: 199 396 396 
    iStrides: 1 396 78804 
    oStrides: 78804 1 199 
    iDist: 31206384
    oDist: 31206384
    direction: -1
    placement: OP
    single-precision
    array type: CI -> HI
    SBRC_Trans_Type: NONE
    Direct_to_from_Reg: FORCE_OFF_OR_NOT_SUPPORT
    OB_TEMP -> OB_USER_OUT
    T -> B
    Leaf-Node: external-kernel configuration: 
        workgroup_size: 0
        trans_per_block: 1
        radices: [ ]
GridParams
  b[22053,1,1] wgs[128,1,1], dy_lds bytes 0
  b[1,112,396] wgs[64,16,1], dy_lds bytes 0
  b[172498,1,1] wgs[60,1,1], dy_lds bytes 720
  b[1,156816,1] wgs[256,1,1], dy_lds bytes 0
  b[4,2451,1] wgs[64,16,1], dy_lds bytes 0
  b[1,112,199] wgs[64,16,1], dy_lds bytes 0
  b[173369,1,1] wgs[60,1,1], dy_lds bytes 720
  b[1,137,199] wgs[64,16,1], dy_lds bytes 0
  b[44328,1,1] wgs[64,1,1], dy_lds bytes 2816
  b[7,1232,1] wgs[64,16,1], dy_lds bytes 0
  b[1,56,396] wgs[64,16,1], dy_lds bytes 0
  b[173369,1,1] wgs[60,1,1], dy_lds bytes 720
  b[1,69,396] wgs[64,16,1], dy_lds bytes 0
  b[44328,1,1] wgs[64,1,1], dy_lds bytes 2816
  b[7,1232,1] wgs[64,16,1], dy_lds bytes 0
End GridParams
===============================================================================

Kernel occupancy: 16
Kernel occupancy: 2
Kernel occupancy: 32
```

</details>
